parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_HOST): '172.31.0.1'
    env(DATABASE_PORT): '3306'
    env(DATABASE_NAME): 'ddd'
    env(DATABASE_USER): 'root'
    env(DATABASE_PASS): 'root'

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        host:     "%env(DATABASE_HOST)%"
        port:     "%env(DATABASE_PORT)%"
        dbname:   "%env(DATABASE_NAME)%"
        user:     "%env(DATABASE_USER)%"
        password: "%env(DATABASE_PASS)%"
        server_version: '5.7'
        types:
            uuid_binary: Ramsey\Uuid\Doctrine\UuidType
        mapping_types:
            uuid_binary: binary
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        #url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
              is_bundle: false
              type: xml
              mapping: true
              dir: '%kernel.project_dir%/config/mapping/orm/domain'
              prefix: 'App\Domain'
              alias: Domain
