security:
    encoders:
        bcrypt:
            algorithm: bcrypt
            cost: 12
    providers:
        users:
            id: 'App\Infrastructure\User\Auth\AuthProvider'

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api_auth:
            pattern:  ^/api/auth
            stateless: true
            anonymous: true


        api_signup:
            pattern:  ^/api/signup
            stateless: true
            anonymous: true



        secured_area:
            provider: users
            anonymous: ~
            guard:
              entry_point: 'App\Infrastructure\User\Auth\Guard\LoginAuthenticator'
              authenticators:
                - 'App\Infrastructure\User\Auth\Guard\LoginAuthenticator'
            form_login:
              login_path: /login
              check_path: login
            logout:
              path: /logout
              target: /

    access_control:
        - { path: ^/profile/*,   roles: ROLE_USER                    }
        - { path: ^/login,       roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/auth,    roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/signup,  roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/doc,     roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/,        roles: IS_AUTHENTICATED_FULLY       }
